### ISSUE TITLE
Ubuntu 24.04 Noble Numbat ROS1 build

### ISSUE THREAD

**Issue by lucasw** [lucasw/ros_from_src#42]
Upgrade 23.10 to 24.04

Follows #39 

Wasn't able to apt upgrade at first

```
The following packages have been kept back:
  liblog4cxx-dev liblog4cxx15 libruby3.1 ruby3.1
```
```
sudo apt purge liblog4cxx-dev
sudo apt purge libaprutil1
sudo apt autoremove
```

That seemed to clear out the conflicts (by uninstalling most of the debian ros packages and others), now this is running

```
sudo do-release-upgrade -d  # update- don't do this, wait for it to work without -d
```

-> That didn't work too well, didn't have working audio and the networking seemed off- did a full fresh install instead and now looks to be fully working.

**Comment by lucasw** [comment]
It looks like a bunch of apt packages that were available earlier in 24.04 are now unavailable?  The docker file fails the same as a desktop install.  Maybe try again in a few days.

```
E: Package 'liborocos-bfl-dev' has no installation candidate
```

Follow these suggestions: https://askubuntu.com/questions/1493000/how-do-i-find-out-why-a-package-gpac-has-been-removed-from-ubuntu

For now build more things from source, update those instructions as needed.

Could build https://github.com/orocos/orocos-bayesian-filtering from source but skipping any package that uses it for now (people_tracking_filter)

```
touch ./other/people/people_tracking_filter/CATKIN_IGNORE
```

**Comment by lucasw** [comment]
```
Starting  >>> catkin_tools_prebuild                                                                                                                                                                                          
_____________________________________________________________________________________________________________________________________________________________________________________________________________________________
Errors     << catkin_tools_prebuild:cmake /home/lucasw/ros/ros1/ros_from_src_2404_ws/logs/catkin_tools_prebuild/build.cmake.000.log                                                                                          
CMake Error at CMakeLists.txt:12 (message):
  The catkin CMake module was not found, but it is required to build a linked
  workspace.  To resolve this, please do one of the following, and try
  building again.
```

Try building catkin_tools manually

Need to replace distutils
```
sudo apt install python3-setuptools
```

https://setuptools.pypa.io/en/latest/deprecated/distutils-legacy.html

No it isn't catkin tools, it's regular catkin?

```
git clone git@github.com:ros/catkin
```

**Comment by lucasw** [comment]
Wasn't this working fine in 23.10- what's different now?

```
Errors     << vdb_mapping:cmake /home/lucasw/ros/ros1/ros_from_src_2404_ws/logs/vdb_mapping/build.cmake.002.log                                                                                                           
CMake Error at CMakeModules/FindTBB.cmake:270 (file):
  file failed to open for reading (No such file or directory):

    /usr/include/tbb/tbb_stddef.h
Call Stack (most recent call first):
  CMakeLists.txt:17 (find_package)

```

https://github.com/SteveMacenski/slam_toolbox/issues/469

-> `git rm CMakeModules/FindTBB.cmake` (but need backwards compatibility)

**Comment by lucasw** [comment]
A built from source rospack doesn't work for anything except system installed packages, after building and source deve/setup.bash it can't find anything in workspace

```
rospack list
octomap /usr/share/octomap
osrf_pycommon /usr/share/osrf_pycommon
urdfdom /usr/share/urdfdom
```

Probably because devel/setup.bash isn't setting ROS_PACKAGE_PATH?  rospack adds /usr/share itself https://github.com/lucasw/rospack/commit/2ea310d3021e068495db9a0e99746666aa9c0522

Where is ROS_PACKAGE_PATH appended to- are there files inside devel that do it (when they are functioning)

---

The above is for a devel build, try an install - nope no better

---

https://github.com/ros/ros_environment ?  don't have this installed at all, probably should start over and install it from source following the older ros from src instructions.

**Comment by lucasw** [comment]
The rospack failure causes this to fail
```
Errors     << nmea_navsat_driver:make /home/lucasw/ros/ros1/ros_from_src_2404_ws/logs/nmea_navsat_driver/build.make.001.log                                                                                               
[rospack] Error: package 'catkin_virtualenv' not found
find: ‘’: No such file or directory
WARNING: cannot load logging configuration file, logging is disabled
```

Can skip for now by not enabling testing

```
catkin config -DCATKIN_ENABLE_TESTING=False
```

**Comment by lucasw** [comment]
https://launchpad.net/ubuntu/+source/ros-metapackages  - no noble entries



https://tracker.debian.org/pkg/ros-metapackages

> Migration status: Blocked. Can't migrate due to a non-migratable dependency. Check status below.
> Blocked by: [ros-rviz](https://tracker.debian.org/pkg/ros-rviz)

This leads to https://tracker.debian.org/pkg/ros-ros-comm 

> Blocked by: [boost1.83](https://tracker.debian.org/pkg/boost1.83)

That's the boost I have installed though

**Comment by lucasw** [comment]
Look around in recent versions of debian docker images, and make some Dockerfiles here for installing other ros packages

https://hub.docker.com/_/debian

Start with `debian:trixie`

```
# or bookworm
ARG IMAGE=debian:trixie
FROM ${IMAGE}
ARG IMAGE
RUN echo ${IMAGE}

ENV DEBIAN_FRONTEND="noninteractive"

RUN apt-get update -yqq
RUN apt-get upgrade -yqq

RUN apt-get update && apt-cache search ros-core-dev
RUN apt-get update && apt-cache search "Robot OS"

RUN apt-get install -yqq `apt-cache search "Robot OS" | awk '{print $1}' | xargs | sed 's/\n/ /g'`
```

bookworm has ros-core-dev, trixie doesn't

But roscore still works, other packages look reasonable (and as mentioned elsewhere libapriltags is a version that works with cmake).

---

double check right debian version:

```
cat /etc/os-release
```

**Comment by lucasw** [comment]
Current process to get base ros running using https://github.com/lucasw/ros_from_src/tree/ubuntu2404:

```
mkdir -p ~/ros/ros1/full_ros_from_src
cd ~/ros
git clone https://github.com/lucasw/ros_from_src --branch ubuntu2404
cd ~/ros/ros1/full_ros_from_src
~/ros/ros_from_src/git_clone.sh
~/ros/ros_from_src/build.sh
```

```
cd ~/ros/ros1/full_ros_from_src
source ~/ros/ros_from_src/env.sh
source catkin_ws/install/setup.bash
```

After that roscore, rostopic etc. will work

---

The latest changes break in python3.8, maybe create both site-packages and dist-packages or detect which is needed
```
+ ls -l '/home/runner/work/ros_from_src/ros_from_src/staging/ros/local/lib/python3.8/dist-packages//catkin_pkg*'
ls: cannot access '/home/runner/work/ros_from_src/ros_from_src/staging/ros/local/lib/python3.8/dist-packages//catkin_pkg*': No such file or directory
```
---

Next overlay the whole 2404 base_repos.yaml - some of them may be redundant but don't bother screen those out now

**Comment by lucasw** [comment]
Add these repos to the ros_from_src git_clone.sh

```
repositories:
  actionlib:
    type: git
    url: git@github.com:ros/actionlib.git
    version: noetic-devel
  angles:
    type: git
    url: git@github.com:ros/angles.git
    version: master
  bond_core:
    type: git
    url: git@github.com:ros-o/bond_core.git
    version: obese-devel
  geometry:
    type: git
    url: git@github.com:ros-o/geometry.git
    version: obese-devel
  interactive_markers:
    type: git
    url: git@github.com:ros-visualization/interactive_markers.git
    version: noetic-devel
  kdl_parser:
    type: git
    url: git@github.com:ros/kdl_parser.git
    version: noetic-devel
  nodelet_core:
    type: git
    url: git@github.com:ros/nodelet_core.git
    version: noetic-devel
  resource_retriever:
    type: git
    url: git@github.com:ros/resource_retriever.git
    version: kinetic-devel
  rosconsole_bridge:
    type: git
    url: git@github.com:ros/rosconsole_bridge.git
    version: kinetic-devel
  urdf:
    type: git
    url: git@github.com:ros/urdf.git
    version: melodic-devel
```
